### ISSUE TITLE
Incompatibility with Craft 4.15

### ISSUE THREAD

**Issue by elivz** [verbb/verbb-base#2]
### Describe the bug

Any chance you could backport this bug fix to the 4.x branch? Looks like Craft 4.15 updated the Yii version to 2.0.52 and that ArrayHelper error is causing a 500 server error now.

```
Declaration of verbb\formie\helpers\ArrayHelper::flatten(array $data, string $separator = '.'): array must be compatible with yii\helpers\BaseArrayHelper::flatten($array, $separator = '.'): array in /var/www/vendor/verbb/formie/src/helpers/ArrayHelper.php on line 52
```

### Steps to reproduce

1. Upgrade to Craft 4.15.0
2. Try to output a form in the template

### Craft CMS version

4.15.0

### Plugin version

2.0.10

### Multi-site?

No

**Comment by engram-design** [comment]
That function doesn't exist in 2.x of this module. This error would be Formie-specific, which should also be fixed in [2.1.46](https://github.com/verbb/formie/releases/tag/2.1.46).

**Comment by elivz** [comment]
Ah, interesting. Looks like 2.1.46 hasn't shown up on Packagist yet, so I can't upgrade it (and why running `composer update` yesterday didn't fix anything). I'll try again tomorrow.

**Comment by engram-design** [comment]
Sorry about that, should be available via [packagist](https://packagist.org/packages/verbb/formie#2.1.46) now.
